### ISSUE TITLE
Apologetic issue: You blocked me on Twitter

### ISSUE THREAD

**Issue by lazytspo** [Saqliva/Saqliva#1]
Dear Saqliva, i just wanted to apologize for actions i've done to you on Twitter. can you please unblock me? so i can finally see your posts again?

**Comment by Saqliva** [comment]
What's your Twitter account?

**Comment by lazytspo** [comment]
LazytownSporta1

**Comment by lazytspo** [comment]
> What's your Twitter account?

it's @LazytownSporta1

**Comment by Saqliva** [comment]
I'm sorry, but I don't want to unblock your Twitter account. I was offended by your remarks before.
(Translated by DeepL)

**Comment by lazytspo** [comment]
> I'm sorry, but I don't want to unblock your Twitter account. I was offended by your remarks before. (Translated by DeepL)

do it, i swear that i will not offend you ever again, not in the million years

**Comment by Saqliva** [comment]
OK.  I unblock, believing that what you are saying is true.
(Translated by Google)
